#!/bin/bash
if [ -n "$LXC_ROOTFS_PATH" ]; then
  if ! [ -s ${LXC_ROOTFS_MOUNT}/bin/"${0##*/}" ]; then
    install -vD --compare -- "$0" ${LXC_ROOTFS_MOUNT}/bin/
  fi
fi

case ${LXC_HOOK_TYPE} in
  ( start )

  ;;

  ( pre-start )

  ;;
esac

set >> /var/log/${0##*/}.stdout
