#!/bin/bash
case $(systemd-detect-virt) in
  ( none )
  if [ -n "$LXC_ROOTFS_PATH" ]; then
    if ! [ -s "${LXC_ROOTFS_PATH}/bin/${0##*/}" ]; then
      install -vD --compare -- "$0" ${LXC_ROOTFS_PATH}/bin/
    fi
  fi

  set >> /var/log/${0##*/}.stdout
  ;;
esac

case ${LXC_HOOK_TYPE} in
  ( start )

  ;;

  ( pre-start )

  ;;
esac
